version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.8
    labels:
      com.datadoghq.ad.logs: '["prisma"]'
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  mysql:
    image: mysql:5.7
    labels:
      com.datadoghq.ad.logs: '[mysql]'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
  datadog:
    links:
     - prisma # Ensures datadog container can connect to prisma container
     - mysql:5.7 # Ensures datadog container can connect to mysql container
    image: datadog/agent:latest
    labels:
      com.datadoghq.ad.logs: '["datadog"]'
    environment:
     - DD_API_KEY=c74297f4dbe8974b7214e4c6d7b48ba6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/mounts:/host/proc/mounts:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
volumes:
  mysql: